spring.application.name=together
# URL de la base de datos (localhost y el puerto por defecto 3306)
spring.datasource.url=jdbc:mysql://localhost:3306/together?useSSL=false&serverTimezone=UTC

# Credenciales (las que configuraste al instalar MySQL)
spring.datasource.username=root
spring.datasource.password=280590

#La password como variable de entorno
#spring.datasource.password=${DB_PASSWORD}

# Estrategia de JPA: 'update' creará las tablas automáticamente basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=update

# Para ver las consultas SQL que Spring hace en la consola (muy útil al empezar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true